#!/usr/bin/env python

# File autogenerated by soften, do not edit

import setuptools

setuptools.setup(
    name='soften',
    version='0.1.1',
    author='Nicholas Bishop',
    url='https://github.com/nicholasbishop/soften',
    author_email='nicholasbishop@gmail.com',
    packages=['soften'],
    install_requires=[
        'able', 'attrs', 'certifi', 'chardet', 'gitdb2', 'gitpython', 'idna',
        'lictionary', 'numeric-version', 'pkginfo', 'requests',
        'requests-toolbelt', 'six', 'smmap2', 'tatsu', 'tqdm', 'twine',
        'urllib3', 'yapf'
    ],
    entry_points={
        'console_scripts': ['soften = soften.app:main']
    })
