#!/usr/bin/env python

# File autogenerated by soften, do not edit

import setuptools

setuptools.setup(
    name='soften',
    version='0.1.1',
    author='Nicholas Bishop',
    url='https://github.com/nicholasbishop/soften',
    author_email='nicholasbishop@gmail.com',
    entry_points={
        'console_scripts': ['soften = soften']
    })
